### ISSUE TITLE
onnx optimized for distilbert fails with batch > 1

### ISSUE THREAD

**Issue by kamalkraj** [ELS-RD/transformer-deploy#106]
To replicate , run `make docker build` on main branch

with batch 1 1 1
<img width="1679" alt="Screenshot 2022-06-29 at 2 27 38 AM" src="https://user-images.githubusercontent.com/17096858/176286459-03aca53b-2d55-4da2-af46-64d1f47b4448.png">

with batch 2 2 2

<img width="1669" alt="Screenshot 2022-06-29 at 2 24 55 AM" src="https://user-images.githubusercontent.com/17096858/176286367-450af2b8-1cf2-4f90-b24f-e0ddae90e66c.png">

with batch 1 8 8
<img width="1679" alt="Screenshot 2022-06-29 at 2 26 15 AM" src="https://user-images.githubusercontent.com/17096858/176286430-6afb87ad-73b6-4892-b178-fc0f4ae96c1d.png">

@pommedeterresautee 

#84 - The same behaviour is observed for QA model

**Comment by pommedeterresautee** [comment]
fix is merged. Closing
