### ISSUE TITLE
[Question] TensorRT + ONNX Runtime

### ISSUE THREAD

**Issue by MaximilienLC** [ELS-RD/transformer-deploy#119]
Hi, I was wondering what your thoughts / experiences were with combining TensorRT & ONNX Runtime.

https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html

**Comment by pommedeterresautee** [comment]
We have found it to be very hard to use IRL. Basically there is a cache system (`ORT_TENSORRT_ENGINE_CACHE_ENABLE`) which recompiles the model for each change of input shape. So you can pad input (which means burning computation for nothing) or it recompiles model from time to time. TensorRT is very slow at compiling.
I can see it useful for images where input shapes are mostly fixed (at least on some nnet) but not for NLP in general.

When you compile yourself outside of ORT you can provide your own range of shapes and at least it's compiled one time for all.

Second point, for mixed precision you need access to the graph to tip TRT which nodes to keep in FP32 which is not doable through Onnx Runtime.

The main advantage is that not supported ops can be delegated to another provider... but IRL for transformers it doesn't happen very often nowadays (it has not always been the case). And when it happened you could just reimplement some kernel with other supported operators (in Roberta I remember we did that like 2 yrs ago).

**Comment by MaximilienLC** [comment]
Thank you for this thorough response :)
