### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by hussius** [ELS-RD/transformer-deploy#12]
The line 

`pip3 install .[GPU] -f https://download.pytorch.org/whl/cu113/torch_stable.html`

did not work for me as written, but it did with quotes:

`pip3 install ".[GPU]" -f https://download.pytorch.org/whl/cu113/torch_stable.html`

Also, the instructions say

`make docker_build` 

but the Makefile does not contain such a rule, only `build_docker` so the command should probably be

`make build_docker`.

**Comment by pommedeterresautee** [comment]
thanks a lot @hussius , I will fix the README.
