### ISSUE TITLE
Support converting T5 model

### ISSUE THREAD

**Issue by ayoub-louati** [ELS-RD/transformer-deploy#122]
Add the support of T5 model in our convert script.

fix #120

**Comment by lorepieri8** [comment]
It would be great to see this over the line. I am looking to use https://huggingface.co/declare-lab/flan-alpaca-base.

**Comment by Taytay** [comment]
This is supported now and this can be closed, right?

**Comment by bradfox2** [comment]
> This is supported now and this can be closed, right?

convert-model still fails on a T5 configuration, so guessing no...

@ayoub-louati   Thanks for the great library - any ETA on native T5 support?  Happy to use the notebook method but I am interested in easier process for my team.

**Comment by jonathlela** [comment]
Fixed by #131
