### ISSUE TITLE
query_body.bin contents

### ISSUE THREAD

**Issue by hussius** [ELS-RD/transformer-deploy#14]
With an instance of the triton server up, running the test cURL command from the README file

```
# @ means no data conversion (curl feature)
curl -X POST  http://localhost:8000/v2/models/transformer_onnx_inference/versions/1/infer \
  --data-binary "@demo/query_body.bin" \
  --header "Inference-Header-Content-Length: 160"
```
gives me the error `{"error":"unexpected inference output 'score' for model 'transformer_onnx_inference'"}`. Looking at the [triton_client.py](https://github.com/ELS-RD/transformer-deploy/blob/main/demo/triton_client.py) script, it seems it might be the case that `score` should be replaced by `model_score` in the [query_body.bin](https://github.com/ELS-RD/transformer-deploy/blob/main/demo/query_body.bin) file? However, after that change I still get an error: `{"error":"failed to parse the request JSON buffer: Invalid value. at 160"}%`.

The [triton_client.py](https://github.com/ELS-RD/transformer-deploy/blob/main/demo/triton_client.py) script works fine for me, BTW.

**Comment by pommedeterresautee** [comment]
Thanks for the report, it's an error on my side. I was using `score` as the output name but it didn't match all tasks, so I changed it to output.
To fix the issue, just edit the `json` (the bin file is json concatenated to the string with some special characters to separate them):

```json
{"inputs":[{"name":"TEXT","shape":[1],"datatype":"BYTES","parameters":{"binary_data_size":58}}],"outputs":[{"name":"score","parameters":{"binary_data":false}}]}6   This live event is great. I will sign-up for Infinity.
```
`"name":"score"` -> `"name":"output"`

Let me know if it works for you?

**Comment by hussius** [comment]
It doesn't, but it might be some other issue on my side. I can use the `triton_client.py` instead anyway, thanks!
