### ISSUE TITLE
How to run convert_model in docker instead of local env?

### ISSUE THREAD

**Issue by leon2milan** [ELS-RD/transformer-deploy#16]
how to run `convert_model -m roberta-large-mnli --backend tensorrt onnx pytorch --seq-len 16 128 128 --batch-size 1 32 32` in built docker env?

**Comment by pommedeterresautee** [comment]
Right now, pre-built docker images from Nvidia are based on TRT 8.0.3, unfortunately it's a bit buggy, the code will work but the accuracy won't be good with mixed precision on some models using some patterns. We fixed those issues but only using TRT 8.2. New Nvidia docker image with updated TRT should be realeased in the coming weeks. When they are ready, I will update the documentation to only use docker image as it's more convenient and guarantee that all dependencies are where they need to be.

**Comment by pommedeterresautee** [comment]
Documentation is now updated, and the docker image is online.
Don't hesitate to re open the issue if you have other related question.
