### ISSUE TITLE
How to deploy TrCOR

### ISSUE THREAD

**Issue by SShimmyo** [ELS-RD/transformer-deploy#163]
Hi, 
I'm trying to deploy TrOCR (https://huggingface.co/microsoft/trocr-small-printed) based on encoder and decoder model by using triton inference server. 
However, I could not find any examples to deploy them. 
I would be great if you share example codes.

**Comment by ayoub-louati** [comment]
Hello @luenberger,
we are working on T5 conversion (which is based on the encoder decoder architecture) in this PR:
https://github.com/ELS-RD/transformer-deploy/pull/131
so you can take a look and you'll a find a very good example.

**Comment by SShimmyo** [comment]
Sorry for the late reply. Thank you for the information. I'l take a look at it.
