### ISSUE TITLE
Support private HuggingFace Hub models?

### ISSUE THREAD

**Issue by sam-writer** [ELS-RD/transformer-deploy#17]
I think in order to support private HF Hub models, invocations of `.from_pretrained`, e.g. [here](https://github.com/ELS-RD/transformer-deploy/blob/main/src/transformer_deploy/convert.py#L99), would need to have a parameter, `use_auth_token`. This parameter defaults to `None`. Setting it to `True` uses a local cached auth token (from calling `$ transformers-cli login`). It can also be set to a string, the API Key, found at https://huggingface.co/settings/token (or https://huggingface.co/organizations/ORG_NAME/settings/token for organizations).

Would you be open to a PR which adds this? I did something [similar in fastT5](https://github.com/Ki6an/fastT5#private-huggingface-model-hub-models).

**Comment by pommedeterresautee** [comment]
good idea, please, do it.
