### ISSUE TITLE
Support other tasks/architectures?

### ISSUE THREAD

**Issue by sam-writer** [ELS-RD/transformer-deploy#18]
First off: thank you! This is a great project, I'm really grateful you released it publically.

From what I can tell, this supports encoder-only architectures, and the Sequence Classification task ([ex](https://github.com/ELS-RD/transformer-deploy/blob/main/src/transformer_deploy/convert.py#L99)). Am I correct? If so, are there plans to support, or interest in supporting, other architectures (encoder/decoder, decoder-only) and/or tasks (Token Classification and Masked token prediction for encoder-only architectures, or Seq2SeqLM for the other architectures)?

**Comment by vblagoje** [comment]
I'd love to know this as well. Also, how would one support (or just speed up) GenerationMixin utility methods: generate(), greedy_search(), sample(), beam_search() etc?

**Comment by vblagoje** [comment]
@sam-writer I found NVidia blog [post](https://developer.nvidia.com/blog/optimizing-t5-and-gpt-2-for-real-time-inference-with-tensorrt/) and their Github [repo](https://github.com/NVIDIA/TensorRT/tree/release/8.2/demo/HuggingFace) with TensorRT counterparts for T5, and GPT-2 useful. It looks like one would need to create TensorRT equivalents for other model architectures. LUK if you find any other useful resources.

**Comment by pommedeterresautee** [comment]
Right now it only supports end to end classification task. There is no real reason for this limitation, it should be easy to extend to other tasks like token classification (NER, etc.), multi choice questions, question answering, etc. What task do you need to have support with? (for encoder only models)

Regarding the encoder only support, it's a choice, right now our priority is in a better direct TensorRT support (no ORT), in particular GPU int-8 quantization should come rapidly (we made it work for Roberta plus we have a generic method with some trade-off).

AFAIK conversion to ONNX of the main generative models is quite easy (T5, Bart, and GPT-2). Regarding TensorRT... it's another story.
Tks @vblagoje for the link, check also https://github.com/NVIDIA/TensorRT/issues/1642 (I have not tried it myself), but I understand that it only work for corner cases (like the HF demo only done on very short sequences).

**Comment by sam-writer** [comment]
> it should be easy to extend to other tasks... for encoder-only models

I agree! Token classification is top of my list for encoder-only model tasks

About the rest: are you saying that the top priority now is to get Triton using the TRT, not ORT, backend?

I am imagining using `transformer-deply` to take ~any popular HF model and give me a triton server to communicate with it, even if it can't do anything with TRT. Is this the goal?

**Comment by pommedeterresautee** [comment]
Both backends (ORT and TRT) are important. ORT works out of the box, so hopefully there is nothing to do for now (may be checking that nothing broke with the recent v.1.10).
TRT requires some work, but deliver significant perf boost in both quantization and mixed precision, that is why it gets the focus right now.

The goal is indeed to take any transformer model (from HF and probably from FAIR), easily optimize it and put it in Triton, so user has not to care about TRT or ORT, it should just work from HTTP requests.

ORT is a great tool with much better capacity to adapt any graph/operator (with multiple backends, etc.), it should always be an option to use it. And for the architectures supported by TRT... the user will have the choice.

**Comment by pommedeterresautee** [comment]
FYI we started to work on GPT-2 and T5 support.
We will take inspiration from Nvidia TRT repo, however, their code is more benchmark oriented than anything else.
It requires some rewriting before being integrated here.

**Comment by sam-writer** [comment]
Yes, I have played with that code. For me the hard part was Triton setup for the stateful backend. Really excited to see this!!
