### ISSUE TITLE
nvidia-pyindex installation

### ISSUE THREAD

**Issue by vishalsrao** [ELS-RD/transformer-deploy#26]
Installation of packages which depend on nvidia-pyindex fail if nvidia-pyindex is not installed before installing transformer_deploy.
My initial guess was that this occurs because setuptools does not install packages in the order specified in the extras_require argument. I tried adding the package to setup_requires & install_requires arguments of setuptools.set in setup.py, but it did not help.

**Comment by pommedeterresautee** [comment]
I think the best solution is to separate Nvidia dependencies from ONNX Runtime ones and for those needing TensorRT, the documentation would mention the possibility to just use Docker image. 
Are you planing to use TensorRT deployment?

**Comment by pommedeterresautee** [comment]
Does `pip3 install ".[GPU]" -f https://download.pytorch.org/whl/cu113/torch_stable.html --extra-index-url https://pypi.ngc.nvidia.com` works out of the box for you?

**Comment by vishalsrao** [comment]
Thanks, @pommedeterresautee. I am not experiencing the issue with the latest version of the code.
