### ISSUE TITLE
GPT-2 pipeline?

### ISSUE THREAD

**Issue by C00reNUT** [ELS-RD/transformer-deploy#31]
Hello, 
thank you for this wonderful implementation. 

Do you have any plans implementing notebook with gpt-2 support?  
It seems that there would be huge speed benefit, especially with smaller sequence lengths and higher batches.

**Comment by pommedeterresautee** [comment]
Yes, it's planned to add support for GPT-2, T5, and Bart. But work has not yet started. Would you mind to share with me what feature you are mainly interested into?

**Comment by C00reNUT** [comment]
> Yes, it's planned to add support for GPT-2, T5, and Bart. 

Great! Nice to hear that. There has been lots of simplification with huggingface and some other transformer libraries, but there is still not a simple library for text generation using recent optimization techniques. Something that would be as simple as [https://github.com/minimaxir/aitextgen](https://github.com/minimaxir/aitextgen).

Although I have recently seen [https://developer.nvidia.com/blog/optimizing-t5-and-gpt-2-for-real-time-inference-with-tensorrt/](https://developer.nvidia.com/blog/optimizing-t5-and-gpt-2-for-real-time-inference-with-tensorrt/). But I haven't tried it yet.

> Would you mind to share with me what feature you are mainly interested into?

Mostly single GPU GPT-2 text generation interface + fine-tuning. 

Thank you for your work!

**Comment by pommedeterresautee** [comment]
The version from Nvidia has been written for reusability and readability, we will probably start there. It covers both T5 and GPT-2.
https://github.com/NVIDIA/TensorRT/tree/main/demo/HuggingFace

**Comment by C00reNUT** [comment]
Great I will give it a try. Thank you.
