### ISSUE TITLE
Docker image timeout

### ISSUE THREAD

**Issue by JonathanLehner** [ELS-RD/transformer-deploy#39]
Error response from daemon: Get https://ghcr.io/v2/: proxyconnect tcp: dial tcp: lookup http.docker.internal on 192.168.65.5:53: read udp 192.168.65.4:63771->192.168.65.5:53: i/o timeout

I cannot download the docker image!

**Comment by pommedeterresautee** [comment]
Hi Jonathan, what command do you use?

**Comment by pommedeterresautee** [comment]
no answer since 1 month, closing
