### ISSUE TITLE
quantized model inference slow with Triton server than inference directly in python code(notebook)

### ISSUE THREAD

**Issue by Jaeker0512** [ELS-RD/transformer-deploy#56]
I follow the guide **_quantization_end_to_end.ipynb_** to quantize my custom classification model base on **Roberta-base-12layers** and finally get the following Latency measures from different backend, the results looks good:
**batch size = 1
seq_length = 128
device = GPU Tesla T4**

> [Pytorch (FP32)] mean=9.66ms, sd=0.19ms, min=9.38ms, max=10.08ms, median=9.60ms, 95p=10.07ms, 99p=10.08ms
> [Pytorch (FP16)] mean=9.84ms, sd=0.25ms, min=9.77ms, max=12.27ms, median=9.80ms, 95p=9.93ms, 99p=10.01ms

> [ONNX (FP32)] mean=8.41ms, sd=0.70ms, min=7.92ms, max=10.01ms, median=8.08ms, 95p=10.00ms, 99p=10.01ms
> [ONNX (FP16)] mean=2.57ms, sd=0.07ms, min=2.40ms, max=3.10ms, median=2.57ms, 95p=2.62ms, 99p=2.63ms

> [TensorRT (FP16)] mean=2.54ms, sd=0.46ms, min=2.32ms, max=3.94ms, median=2.39ms, 95p=3.92ms, 99p=3.93ms
> [TensorRT (INT-8)] mean=1.98ms, sd=0.17ms, min=1.87ms, max=3.57ms, median=1.95ms, 95p=2.06ms, 99p=2.30ms

but after I deployed the **ONNX FP16 model** and **TesorRT model (both FP16 and INT-8 )** with Triton Server and then do stress test with **Jmeter** , the result showed that TensorRT INT-8 model is not faster than FP16 model:
**batch size = 1
seq_length = 128
threads = 20
GPU utilization between 93%~95%**

> Triton server with TensorRT INT-8 model, **throughput = 398.7/sec**
> Triton server with TensorRT FP16 model, **throughput = 399.1/sec**
> Triton server with ONNX FP16 model, **throughput = 363.3/sec**

I just wonder what's wrong with the Triton Server, is it has a "int8 inference" option and I didn't turn it on?

**Comment by pommedeterresautee** [comment]
No there is no such parameter to enable int 8 on Triton.
What is threads = 20 ? (20 parallel calls?)

**Comment by v1nc3nt27** [comment]
I noticed in the post that the speedup between TensorRT (FP16) and TensorRT (INT-8) is not as much as you @pommedeterresautee were observing, so I also finally tested the QAT with quantization_end_to_end.ipynb.

I only changed the model to distilroberta-base, batch size to 64 and sequence length to 60 (saving some GPU memory) and the difference between TensorRT (INT-8) and TensorRT (FP16) is much smaller than expected:

```
[TensorRT (INT-8)] mean=12.98ms, sd=2.28ms, min=10.95ms, max=19.48ms, median=11.97ms, 95p=18.75ms, 99p=19.16ms
[Pytorch (FP32)] mean=77.97ms, sd=1.88ms, min=75.02ms, max=86.88ms, median=77.59ms, 95p=81.05ms, 99p=85.38ms
[Pytorch (FP16)] mean=28.12ms, sd=1.49ms, min=26.31ms, max=40.46ms, median=27.79ms, 95p=29.96ms, 99p=31.88ms
[Pytorch (FP32) - CPU] mean=1048.36ms, sd=129.41ms, min=852.20ms, max=1352.36ms, median=1055.10ms, 95p=1244.75ms, 99p=1330.83ms
[Pytorch (FP16) - CPU] mean=975.21ms, sd=82.05ms, min=850.56ms, max=1185.23ms, median=970.42ms, 95p=1108.68ms, 99p=1169.92ms
[Pytorch (INT-8) - CPU] mean=762.29ms, sd=131.97ms, min=615.92ms, max=1017.71ms, median=725.51ms, 95p=1001.95ms, 99p=1014.56ms
[TensorRT (FP16)] mean=14.29ms, sd=0.72ms, min=13.14ms, max=16.57ms, median=14.26ms, 95p=15.91ms, 99p=16.09ms
[ONNX Runtime GPU (FP32)] mean=68.29ms, sd=6.04ms, min=59.02ms, max=108.15ms, median=66.85ms, 95p=74.73ms, 99p=95.05ms
[ONNX Runtime GPU (FP16)] mean=19.91ms, sd=0.76ms, min=18.07ms, max=22.27ms, median=19.99ms, 95p=21.02ms, 99p=21.43ms
[ONNX Runtime CPU (FP32)] mean=814.14ms, sd=80.10ms, min=723.20ms, max=959.46ms, median=802.24ms, 95p=939.93ms, 99p=955.55ms
[ONNX Runtime CPU (FP16)] mean=843.27ms, sd=51.34ms, min=767.65ms, max=963.77ms, median=830.62ms, 95p=931.32ms, 99p=957.28ms
[ONNX Runtime CPU (INT-8)] mean=788.20ms, sd=54.43ms, min=694.40ms, max=866.73ms, median=794.11ms, 95p=855.83ms, 99p=864.55ms
```

I also tested it for roberta-base with batch size 8 and sequence length 60 and observed the same:

```
[TensorRT (INT-8)] mean=3.88ms, sd=0.38ms, min=3.28ms, max=4.95ms, median=3.89ms, 95p=4.49ms, 99p=4.72ms
[Pytorch (FP32)] mean=20.60ms, sd=1.40ms, min=19.13ms, max=26.43ms, median=19.95ms, 95p=22.94ms, 99p=24.83ms
[Pytorch (FP16)] mean=9.28ms, sd=0.75ms, min=7.90ms, max=11.61ms, median=9.26ms, 95p=10.30ms, 99p=11.56ms
[Pytorch (FP32) - CPU] mean=602.23ms, sd=523.31ms, min=217.97ms, max=2097.06ms, median=407.48ms, 95p=1491.83ms, 99p=1976.02ms
[Pytorch (FP16) - CPU] mean=374.12ms, sd=178.85ms, min=188.02ms, max=668.18ms, median=285.60ms, 95p=666.44ms, 99p=667.83ms
[Pytorch (INT-8) - CPU] mean=266.94ms, sd=187.14ms, min=141.51ms, max=805.70ms, median=220.01ms, 95p=575.49ms, 99p=759.66ms
[TensorRT (FP16)] mean=4.88ms, sd=0.60ms, min=4.58ms, max=6.97ms, median=4.67ms, 95p=6.95ms, 99p=6.96ms
[ONNX Runtime GPU (FP32)] mean=18.09ms, sd=0.36ms, min=17.51ms, max=19.29ms, median=18.02ms, 95p=18.82ms, 99p=19.26ms
[ONNX Runtime GPU (FP16)] mean=5.41ms, sd=0.23ms, min=5.20ms, max=6.77ms, median=5.34ms, 95p=5.86ms, 99p=6.16ms
[ONNX Runtime CPU (FP32)] mean=147.14ms, sd=3.54ms, min=143.84ms, max=155.57ms, median=145.71ms, 95p=153.48ms, 99p=155.16ms
[ONNX Runtime CPU (FP16)] mean=249.77ms, sd=10.18ms, min=237.83ms, max=271.52ms, median=247.37ms, 95p=268.42ms, 99p=270.90ms
[ONNX Runtime CPU (INT-8)] mean=152.41ms, sd=23.31ms, min=133.53ms, max=206.09ms, median=142.05ms, 95p=198.43ms, 99p=204.55ms
```

The experiments are done on a mobile RTX 2080, so I'm a bit limited wrt the memory and cannot test large sequence lengths. I was wondering @pommedeterresautee, if you have any intuition of why I do not experience ~2x speedup with INT-8. Can it be the sequence length?

Unlike @Jaeker0512, however, I see that speedup also in triton, but I'm not using a batch size of 1 (rather 64 or more).
