### ISSUE TITLE
Transforming https://huggingface.co/csarron/roberta-base-squad-v1

### ISSUE THREAD

**Issue by elyast** [ELS-RD/transformer-deploy#57]
Hi,

I wanted double check how we can transform question answering models like the one mentioned above. (It is question answering model - transformers.AutoModelForQuestionAnswering) For example when using vanilla python for your input:
```
{ "question": "Did the stock come down?", "context": "Some text about stocks, with reference if stocks went up or down..." }
```
Q/A pipeline is answering with score, start and end of the sequence and chunk of text (based on start and end), e.g.
```
{"score": 0.02739531360566616, "start": 103, "end": 173, "answer": "sent stocks sliding to their worst performance in months on Wednesday."}
```

after I converted this model as classification model, I am seeing given input:
```
"inputs": [{"name": "TEXT", "shape": [2], "datatype": "BYTES", "data": ["Did the stock come down?", "\Some text about stocks, with reference if stocks went up or down..."]}]}
```
following output:
```
{"model_name":"roberta_onnx_inference","model_version":"1","parameters":{"sequence_id":0,"sequence_start":false,"sequence_end":false},"outputs":[{"name":"output","datatype":"FP32","shape":[1,2],"data":[-0.2091064453125,-0.06671142578125]}]}
```

As probably expected it doesn't really output what it should, I am wondering how we can change/extend the library to generate correct outputs.
Model itself generate set of tensors (the same shape as encoded input) for start and end of sequence https://github.com/huggingface/transformers/blob/master/src/transformers/pipelines/question_answering.py#L371, here I am given just two numbers, so I cannot use the output to invoke postprocessing logic in QA pipeline

Any support appreciate it :).

**Comment by pommedeterresautee** [comment]
QA model requires a post processing to transform model output in span, etc.
I would advise to adapt the Python code run by Triton like we did for generative model to add the post processing.
-> https://github.com/ELS-RD/transformer-deploy/blob/main/src/transformer_deploy/utils/generative_model.py
