### ISSUE TITLE
add more benchmarks

### ISSUE THREAD

**Issue by pommedeterresautee** [ELS-RD/transformer-deploy#6]
* more sizes
* more models

**Comment by narayanacharya6** [comment]
Will you consider adding benchmarks for different CPU architectures?

**Comment by pommedeterresautee** [comment]
right now we are targeting Nvidia GPU mainly as its the main platform we deploy transformer models.
Have you use cases where it makes sense to deploy transformers on CPU?

**Comment by narayanacharya6** [comment]
It makes sense for small teams who don't have access to GPUs or find it costly to use AWS/GCP GPU Compute options. From a workflow standpoint I don't see anything that should stop me from running it on CPUs - I can give it a go myself.

**Comment by pommedeterresautee** [comment]
Ok I understand.
To get best performances, you need to choose wisely your kind of AWS instance (best results are obtained with instruction like VNNI and AVX-512), and if you leverage ONNX Runtime, check the OpenVino backend which should provide very good results. Triton also support OpenVino out of the box.

**Comment by pommedeterresautee** [comment]
benchmarks has been started to be added in #95
