### ISSUE TITLE
convert to onnx model takes more time on CPU

### ISSUE THREAD

**Issue by kamalkraj** [ELS-RD/transformer-deploy#63]
converting model to onnx with device as `cpu` takes around 8 minutes
```bash
docker run -it --rm --gpus all \
  -v $PWD:/project ghcr.io/els-rd/transformer-deploy:0.4.0 \
  bash -c "cd /project && \
    convert_model -m \"distilbert-base-uncased-finetuned-sst-2-english\" \
    --backend onnx \
    --seq-len 16 128 128 --device cpu"
```

The same model is converted to onnx using GPU in less than 2 minutes
```
docker run -it --rm --gpus all \
  -v $PWD:/project ghcr.io/els-rd/transformer-deploy:0.4.0 \
  bash -c "cd /project && \
    convert_model -m \"distilbert-base-uncased-finetuned-sst-2-english\" \
    --backend onnx \
    --seq-len 16 128 128"
```

using huggingface default onnx converter only takes ~20s
```bash
python -m transformers.onnx --model=distilbert-base-uncased-finetuned-sst-2-english --feature sequence-classification    onnx/
```

@pommedeterresautee

**Comment by pommedeterresautee** [comment]
Hi, the conversion itself takes a few seconds. 
At the end of the process there is a benchmark to show latencies on your terminal.
This is the part which takes time, and on CPU it will take more time than GPU.
Hugging Face just does the conversion.

If you don't care use something like `--seq-len 2 2 2`, the inference will be very fast.

**Comment by kamalkraj** [comment]
Thanks @pommedeterresautee
