### ISSUE TITLE
Incorrect demo url in documentation

### ISSUE THREAD

**Issue by vishalsrao** [ELS-RD/transformer-deploy#64]
The link to demo page (https://els-rd.github.io/transformer-deploy/run/demo/infinity) in the documentation page https://els-rd.github.io/transformer-deploy/run/ is not working. I think https://github.com/ELS-RD/transformer-deploy/tree/main/demo/infinity may be the right link.

**Comment by pommedeterresautee** [comment]
Thank you @vishalsrao , I have included the fix in a coming PR
