### ISSUE TITLE
Build OnnxRuntime Error

### ISSUE THREAD

**Issue by brevity2021** [ELS-RD/transformer-deploy#80]
Hi, I was following the compilation steps in the [t5 notebook](https://github.com/ELS-RD/transformer-deploy/blob/main/demo/generative-model/t5.ipynb) to build OnnxRuntime. But when I run 
`git checkout -b fix_if e1c04eed29d48f295de1cfbd48713158537cdaa7`, the output is:
`fatal: reference is not a tree: e1c04eed29d48f295de1cfbd48713158537cdaa7`. 

Previously I ran:
`git clone --recursive https://github.com/Microsoft/onnxruntime
cd onnxruntime` as suggested.

I wonder what is the reason?

**Comment by pommedeterresautee** [comment]
that is because I have failed in copy pasting the commit :-(

try with:
`git checkout -b fix_if 81d78706feb1dc923f3e43f7ba8ac30b55f5b19b`

Thank you for the report, I will fix it!

**Comment by pommedeterresautee** [comment]
Issue fixed, closing
