### ISSUE TITLE
Output difference between ONNX and Pytorch in T5 notebook

### ISSUE THREAD

**Issue by VikasOjha666** [ELS-RD/transformer-deploy#81]
Hi @pommedeterresautee Just checked out the latest T5 optimization notebook . Everything seems to be working well for T5-base pretrained model from huggingface but when I am trying to optimize model from valhalla/t5-base-qa-qg-hl. I am noticing difference in output between the two.

Below is code snippet modified from T5 notebook.

input_text='''<hl> Python <hl> is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum \
and first released in 1991, Python's design philosophy emphasizes code \
readability with its notable use of significant whitespace.'''
inputs=tokenizer(input_text,return_tensors="pt")
input_ids=inputs.input_ids.cuda()

torch.cuda.synchronize()
with torch.inference_mode():
    print("Onnx:")
    print(
        tokenizer.decode(
            model_gen.generate(
                inputs=input_ids,
                min_length=3,
                max_length=60,
                num_beams=4,
                no_repeat_ngram_size=2,
            )[0],
            skip_special_tokens=True,
        )
    )
    print("Pytorch:")
    print(
        tokenizer.decode(
            pytorch_model.generate(
                input_ids=input_ids,
                min_length=3,
                max_length=60,
                num_beams=4,
                no_repeat_ngram_size=2,
            )[0],
            skip_special_tokens=True,
        )
    )

And below are the outputs:

Onnx:
What is an interpreted, high-level, general-purpose programming language?
Pytorch:
What language was created by Guido van Rossum?

**Comment by VikasOjha666** [comment]
@pommedeterresautee  For some reason I found addition of space or </s> which is required by previous version of transformer is creating this issue. Removing it from input is solving the issue but the question is that what impact this model will have in production?

**Comment by pommedeterresautee** [comment]
It's expected that the produced text is not always the same. There are rounding differences between the two and you need just one different generated token to get very different sequences. 
On average the quality should be similar, is it the case?

To reduce the difference with original model, you can skip the fp16 conversion. The inference will be slightly slower but not a lot as with the cache support the computation intensity is lower. The main impact is on the ram but depending of the len of the generated text it may be ok for you.

**Comment by VikasOjha666** [comment]
@pommedeterresautee Okay thanks.Will experiment and let you know.

**Comment by pommedeterresautee** [comment]
closing as there is no more activity. Please don't hesitate to reopen
